"""Generate/check additive shared schemas and TypeScript handoff types, without frontend edits."""

import argparse
import json
import sys
from pathlib import Path
from typing import Any

BACKEND_ROOT = Path(__file__).resolve().parents[1]
ROOT = BACKEND_ROOT.parent
sys.path.insert(0, str(BACKEND_ROOT))
from app.contracts import learning

NAMES = (
    "AggregationConsent",
    "CoverageBatch",
    "DeliveryBatch",
    "ProfessorMetrics",
    "ExternalTextConsent",
    "RecoveryDraft",
    "RecommendationReport",
    "RecommendationReview",
)


def ts_type(schema: dict[str, Any]) -> str:
    """Translate the generated JSON Schema subset into a reusable TypeScript type."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return "Array<" + ts_type(schema["items"]) + ">"
    if kind == "object":
        required = schema.get("required", [])
        return (
            "{ "
            + " ".join(
                f"{key}{'' if key in required else '?'}: {ts_type(value)};"
                for key, value in schema.get("properties", {}).items()
            )
            + " }"
        )
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def artifacts() -> dict[Path, str]:
    """Return deterministic schema/type text with JSON Schema as the review artifact."""
    outputs = {}
    definitions = {}
    for name in NAMES:
        model = getattr(learning, name)
        schema = model.model_json_schema()
        schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
        stem = "".join(
            "_" + char.lower() if char.isupper() else char for char in name
        ).lstrip("_")
        outputs[ROOT / "shared/contracts" / (stem + ".schema.json")] = (
            json.dumps(schema, indent=2, sort_keys=True) + "\n"
        )
        definitions.update(schema.get("$defs", {}))
        definitions[name] = schema
    header = "// Generated by backend/scripts/generate_learning_contracts.py. Do not edit.\n// Integer ranges and privacy constraints require runtime schema validation.\n"
    outputs[ROOT / "shared/contracts/generated/learning_types.ts"] = (
        header
        + "\n".join(
            f"export type {name} = {ts_type(schema)};"
            for name, schema in sorted(definitions.items())
        )
        + "\n"
    )
    return outputs


def main() -> int:
    """Write outputs, or exit nonzero when --check finds schema or type drift."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in artifacts().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("Stale contracts: " + ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
