"""Generate/check Feature 7 JSON Schema and TypeScript contract artifacts."""

import argparse
import json
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_ROOT))

from app.demo.routes import DemoRunRequest
from app.demo.runner import DemoRunResult
from scripts.generate_learning_contracts import ts_type


def artifacts() -> dict[Path, str]:
    """Return deterministic demo schemas and types, without filesystem mutations."""
    outputs = {}
    definitions = {}
    root = BACKEND_ROOT.parent / "shared/contracts"
    for model, stem in (
        (DemoRunRequest, "demo_run_request"),
        (DemoRunResult, "demo_run_result"),
    ):
        schema = model.model_json_schema()
        schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
        outputs[root / f"{stem}.schema.json"] = (
            json.dumps(schema, indent=2, sort_keys=True) + "\n"
        )
        definitions.update(schema.get("$defs", {}))
        definitions[model.__name__] = schema
    outputs[root / "generated/demo_types.ts"] = (
        "// Generated by backend/scripts/generate_demo_contracts.py. Do not edit.\n"
        "// Runtime schema validation still enforces ranges and privacy rules.\n"
        + "\n".join(
            f"export type {name} = {ts_type(schema)};"
            for name, schema in sorted(definitions.items())
        )
        + "\n"
    )
    return outputs


def main() -> int:
    """Write demo contracts; --check reports drift with exit code 1, never writes."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in artifacts().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(BACKEND_ROOT.parent)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("Stale demo contracts: " + ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
